apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-webserver
  namespace: nebyri
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helm-webserver
  template:
    metadata:
      labels:
        app: helm-webserver
    spec:
      containers:
        - name: helm-webserver-container
          image: {{ .Values.imageName }}
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /hostname
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /hostname
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: AUTHOR
              value: {{ .Values.authorName }}
---
apiVersion: v1
kind: Service
metadata:
  name: my-webserver-service
  namespace: nebyri
spec:
  type: ClusterIP
  selector:
    app: helm-webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000