apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: nebyri
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver-container
          image: nebyri/devopscloudrucamp:latest
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /hostname
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /hostname
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: nebyri
spec:
  type: ClusterIP
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000